branches:
  except:
  - "/^flux-*/"
services:
- docker
before_install:
- docker pull nubisproject/nubis-travis:master
jobs:
  include:
  - stage: build
    script:
    - docker run --mount type=bind,source="$(pwd)",target=/nubis/files nubisproject/nubis-travis:master
    - docker build -t airmozilla .
    - docker tag airmozilla "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT"
    - docker images
  - stage: push
    if: env(DOCKER_USERNAME) IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT"
  - stage: release
    if: tag IS present
    script:
    - docker tag "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT" "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_TAG"
env:
  global:
  - secure: srHjKVbyaopeOjAJ6TmUJg9//c5R1W8UM9/1cZUJaCTBe+klvY4/x+2DcMb8DZwk8YwJKxEikAsF+9t2Awm3gD9pJCFyvIUMChV+iBo8hcSoTZuBqDZ1gmyOdOu9S8+s0nB3LThQKAXkCOVMr5O+H0n1d0BUesqwJHpuJcq4gfu1gdia/GF9kqwH1lST8SBsRZlpWp7US6GiBNMubDIA5q/g+JiJGIshnBr0L/Spb5tbcJAnf8BMA0LX+Vz6mjjQdyp6rnFVwtxWK26MGUmpGXdm7GMEdDBFzu0hy3iWybZREudXW5oFqjnS3R/4YjH7Uec3VHgFOWf9QsVYe1IZvAF1aUUxGyCXonsmbXHy5gddJXqQoObU+VlrfOGx6MTaP0R8r1I8inOLLvWuX3Y7b+j3hb1MOtOLmETkaXPfVuTZj9M15eAJITGAD1C43Sw+b6kRcbayLqAMig6ZinRK25m37CtZ97uxjqHTHXCwTouyXtBUU957MIeB5urvyufRYYkPpPTbAuhCHluQsVYV2j4+ZhRQwN5zWIBLa41C2zfLyZmIJ03FFZastcqF493VKTlTecoLG41ZTo+esussJ/BVLlhUY3ZWzrz2Rwi4M/CtizEDoK1K8uzobxOHA4k/QO8quhA+abNUO0Gv4niWP97JopZx8q6WGZ83ZEKfFtM=
  - secure: d8WVneG7cyB9ktjZ9OPJH6l0CwbeVxZLTVDWzlkJB2GHx52sSmo3m7ru2VTHFE7Zs5JBfQyfL445Y7hYZGH9eh0TMcwsmzOvCGQ6kM3zgmtOvUG8YL9oRKHLQfwoaWgDs0nKv1aOu5FpbeI7Em5nxTr1bphvf/hPLC/VQxyv9yUr2Lx6ZwOlcunGfrCzIzOHqzkz3boauPKbe00RQM+5qJls8E3SvDZ+SRBs0rd8+4/VyEhFaNsN6LlmtmEJ/qI0CKG6jKmkVqn5cxL9myHLi8E5ccb0aeEHkxx9kuh7sma72/kA9yM4KmOR6LkS0YwDJz03D6Lu9AKqX1qklzNYibaZM/ZLZz2NerN7HPj6y1IbWbzbzdngLE8x4aO1j0muGDrW9HIxhOeGsgYDKDsmuVqwS6s9k5+A+HcPNK8BXfSZ8lX2o/9JG84ucvbsYj8f+C0SnHfKoh+bO4uA3sBPZ10r9JWMWNNhmI4qY+CX6qc2iecD7lYIzV5KApcHEoxHRTOvO1QLFY6awljjrEULSIGhHYax8pTF5rT8L1JijccduUO7+vw5H/bBTqEox407hHaF9TSqvAin142KX9wQyWvL/gFlFKlUhGCz0B8o/YjAX6hhSh01eGYotmxZG7gW3d8TD2vp6/RyrbPKBST3VHGk78fVa6uAMGqgdC11kpw=
notifications:
  slack:
    secure: JmYu6s3PPfLts43WE7lkc5lmbLMYkMZw+Dz0RYOC5Y0vmfmyTEeHDa75YiTOYLeDnkGxedsiMsZ7u4wbIesMst3lbNOYBdEX+UOvp+/oI2+OSOEitdzVhAXC65knPp4wPJCOM5cq5gqOcg+Mhz+uo/MzZebGtLmuuLNfAMcv+M/B5HcQNSmqT9v3waaNQRJjONI5zqS4b+VQJLWvFAjQTR7FV+Jbo5Q1vxz+75c0EL1xjTE5zbHWgYfSUjgEB3N32mEVmxVwdms+yfbk2wLa3uITgfHjUZRye5QMyFEpOAG5fprm7n/jpWc0ab9nkIx/nmMeSBP8vuQt7FCYGOpvLBrZ1f7P9AIuuDa3ULm2ftCtsQejfPsjDKXhqd3Yw9troAgU0sIGJVErviZ3GEZiqISIyPPNS+uAJ7ljtBYNB2kEueuDJjIN9uKFM+36m/AiUQeYcRouKjbU4DyZ8ILAUUx8SLTaMZCzzN16yn4dzT/M9dHHhQGGbQ2uiPZJGrBE6H9wgrH36ALfn1WkBP0uh//T5JMTdkVgH1mHeGX7dLN82rtDkxZf5RkZo0e91YxRDYN2iPTEyhRA68gJ81oxpV28Lpo35RngOCSrLc7lV2KSmgXj4VL2Bap+mBMAJi5GvsHisJFr8EoeBzBXUrk/yD9egRrEETxgdoEIBOGEUmc=
