branches:
  except:
  - "/^flux-*/"
services:
- docker
before_install:
- docker pull nubisproject/nubis-travis:master
jobs:
  include:
  - stage: build
    script:
    - docker run --mount type=bind,source="$(pwd)",target=/nubis/files nubisproject/nubis-travis:master
    - docker build -t airmozilla .
    - docker tag airmozilla "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT"
    - docker images
  - stage: push
    if: env(DOCKER_USERNAME) IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT"
  - stage: release
    if: tag IS present
    script:
    - docker tag "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_COMMIT" "itsre/airmozilla:$TRAVIS_BRANCH-$TRAVIS_TAG"
notifications:
  slack:
    secure: JmYu6s3PPfLts43WE7lkc5lmbLMYkMZw+Dz0RYOC5Y0vmfmyTEeHDa75YiTOYLeDnkGxedsiMsZ7u4wbIesMst3lbNOYBdEX+UOvp+/oI2+OSOEitdzVhAXC65knPp4wPJCOM5cq5gqOcg+Mhz+uo/MzZebGtLmuuLNfAMcv+M/B5HcQNSmqT9v3waaNQRJjONI5zqS4b+VQJLWvFAjQTR7FV+Jbo5Q1vxz+75c0EL1xjTE5zbHWgYfSUjgEB3N32mEVmxVwdms+yfbk2wLa3uITgfHjUZRye5QMyFEpOAG5fprm7n/jpWc0ab9nkIx/nmMeSBP8vuQt7FCYGOpvLBrZ1f7P9AIuuDa3ULm2ftCtsQejfPsjDKXhqd3Yw9troAgU0sIGJVErviZ3GEZiqISIyPPNS+uAJ7ljtBYNB2kEueuDJjIN9uKFM+36m/AiUQeYcRouKjbU4DyZ8ILAUUx8SLTaMZCzzN16yn4dzT/M9dHHhQGGbQ2uiPZJGrBE6H9wgrH36ALfn1WkBP0uh//T5JMTdkVgH1mHeGX7dLN82rtDkxZf5RkZo0e91YxRDYN2iPTEyhRA68gJ81oxpV28Lpo35RngOCSrLc7lV2KSmgXj4VL2Bap+mBMAJi5GvsHisJFr8EoeBzBXUrk/yD9egRrEETxgdoEIBOGEUmc=
DOCKER_USERNAME:
  secure: ssXlpWLosLZPfV6+Y6Jf9QFKeUM4dqapNhfRkJndYQEPHqe64e63E0cAzXHMRljdBJghz3j1OMoN2bhgelA0Vz+s75jFg3TAl4r/rGAFhnSWbKHFCtHTHzQ8QlgPmDM++Xqpen7OQ2C2Sio/dTnhdSx0wNXZrkB/HOQzmg72EDqLjpZsNItf7eJNyIZcFd+XCscuVqLerpjf9QxVQ7CCKLM7LEPDCz9o4T64q8aqe1H7GCA+K8EZesbn+sZdmxj5Zy4Of+sa3BCGBeiWaw4gdQT7J1KiWPwwh5kL80hO5s2M8VO8BO2YGVXS03OET260iIiNmDl/zA27FIiHYNAXWZTpJXV/CPz1LL6cryfsStVtos+XdzY+rvmR7CM/+R0er93pr9UCFs3PBlDtxehBqlTdn08Y66nJNmpsPI3sjYZPvwLe3qE+SMsSYvpfRRdLZPS0/PRVMAkYzEi474Sc0Fp/R5qjZUGJxfQwoJzNDvi4kcWkIikVF84dOugkSCcchGp8nWZeyItPwATBUqmc5S+eC4+Lz9tRSZEReigcit2M9cRZEUUF8xSByz8A8SHfZ4bRgHFzpRNpWcKnZj7YVMtRcwAFFJATV5crobsl0YW8STKvVhEiXMKuUbYKYb2SvVZnR1VMuqBSZUNf+uvZbb/29B7AlTt06tF7MViRkoE=
DOCKER_PASSWORD:
  secure: WTefAaIIrOcHNEBS23xD2mxexBlItqr2TligrsZT4LIHuoPu7vLqI0FT6G46alp3cxcwx79WtFmeN5WAZJ5zpKgT+RkesLHcdAmCC6zLZ4WXDtQpf88jEilHYzdDg1ivon3liA4yY7ayGVL9D8IJv/t9z1FJfMAY/wPlSxuDzmwi4g1Lb0ph77XMhLTD+XTdoslLpXuA7jnuhio8NSqwHRgWNjmgnuNewkx432iIq7M3lL0bxF5ICDvdui7UV9DvHj00ky/rpbeRVK7TLnSLCXcxGlKONEpuQYrq7nQklLG4sv+XCDjla7uBWSiSzkcttijkfRIsbqa8YHoFZtwSG83y1lstL2T3AJcntx2Izrwg7UQYLsEuwxq3W2SmuK1yK+ZCOZbFjYVNI7EpPOe3slh2mLtKIIb52e/SBmGzkKeciBA3Iqjv147i2qgZIUssHyUHXI6VyltLDjoSQ6qd17Useqaftc66vCTQnCCN0l5ejaqftkgbO9E4GRO/OLwfpmXjTLKtnVXE8LIVrVqjAtt03yflRLGDmFbfa3RdQjwhHIByIzxhWHorMo2QloJOiB47fge/+1vJAtTH4Is9fJ3hQhTu5Qwm+QRi6J1cfcCrtXA0+00idNiMyeKgpmy5qw1c7KqE6Wz17vFAJq/E8QCaBMQQk1Cx31ZX08PCZ/4=
