---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-prod
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-5946f35f1b9cbf970cd871a47b4fa9ef969562d4
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-5946f35f1b9cbf970cd871a47b4fa9ef969562d4
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-5946f35f1b9cbf970cd871a47b4fa9ef969562d4
        name: migrate
