---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-prod
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-d5580073b11c82868a35aea89911d0a95e2b1104
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-d5580073b11c82868a35aea89911d0a95e2b1104
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-d5580073b11c82868a35aea89911d0a95e2b1104
        name: migrate
