---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-prod
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-d7d8e6a5c9e3d2c1e3746b7d844b3909e5f8d9d3
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-d7d8e6a5c9e3d2c1e3746b7d844b3909e5f8d9d3
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-d7d8e6a5c9e3d2c1e3746b7d844b3909e5f8d9d3
        name: migrate
