---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-prod
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-e65bc9f902e33da13b2d19e4c153b120cc7bba2a
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-e65bc9f902e33da13b2d19e4c153b120cc7bba2a
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-e65bc9f902e33da13b2d19e4c153b120cc7bba2a
        name: migrate
