apiVersion: kustomize.config.k8s.io/v1beta1
namespace: airmozilla-prod
kind: Kustomization
bases:
 - ../common
patchesStrategicMerge:
- releases-patch.yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: airmozilla
  path: ingress_patch.yaml
commonLabels:
  environment: prod
