---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:783633885093:certificate/2b308374-1a39-4f67-9a6e-83dfd882f32a
  name: ingress-nginx
