---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airmozilla-events
  namespace: airmozilla
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.web: glob:k8s-*
spec:
  # Should be hourly but we are not ready yet
  schedule: "@daily"
  # Dont run in parallel
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
          - name: airmozilla-events
            image: itsre/airmozilla:1
            args:
            - /usr/local/bin/python
            - /app/manage.py 
            - refresh_events
            env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.host
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.name
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.password
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: region
            - name: PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: provider
            - name: INXPO_AUTH_CODE
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.auth_code
            - name: INXPO_USER_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.user_credentials
            - name: INXPO_SHOW_KEY
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.show_key
            - name: INXPO_SHOW_PACKAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.show_package_key
