---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airmozilla-events
  namespace: airmozilla
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: airmozilla-events
          containers:
          - image: itsre/airmozilla:k8s-e842ac95313f0af74cd85566dfd1231f02483074
            name: airmozilla-events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla-deployment
  namespace: airmozilla
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: itsre/airmozilla:k8s-e842ac95313f0af74cd85566dfd1231f02483074
        name: web
