---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  annotations:
   flux.weave.works/automated: "true"
   flux.weave.works/tag.events: "glob:master-*"
spec:
  # Should be hourly but we are not ready yet
  schedule: "@daily"
  # Dont run in parallel
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
          - name: events
            image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/airmozilla:k8s-ee2a5285e00a73ef76758f060bdb9d19cd005a0d
            args:
            - /usr/local/bin/python
            - /app/manage.py
            - refresh_events
            env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.host
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.name
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: database.password
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: region
            - name: PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: airmozilla-resources
                  key: provider
            - name: INXPO_AUTH_CODE
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.auth_code
            - name: INXPO_USER_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.user_credentials
            - name: INXPO_SHOW_KEY
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.show_key
            - name: INXPO_SHOW_PACKAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: airmozilla-secrets
                  key: inxpo.show_package_key
