---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
spec:
  selector:
    matchLabels:
      app: airmozilla-web
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: airmozilla-web
    spec:
      initContainers:
      - name: migrate
        image: itsre/airmozilla:k8s-ee2a5285e00a73ef76758f060bdb9d19cd005a0d
        command:
          - python
          - manage.py
          - migrate
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 256Mi
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.host
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.name
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.username
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.password
      containers:
      - name: web
        image: itsre/airmozilla:k8s-ee2a5285e00a73ef76758f060bdb9d19cd005a0d
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
            path: /healthz
        readinessProbe:
          httpGet:
            port: 80
            path: /readiness
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 256Mi
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.host
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.name
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.username
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: database.password
          - name: REGION
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: region
          - name: PROVIDER
            valueFrom:
              configMapKeyRef:
                name: airmozilla-resources
                key: provider
          - name: INXPO_AUTH_CODE
            valueFrom:
              secretKeyRef:
                name: airmozilla-secrets
                key: inxpo.auth_code
          - name: INXPO_USER_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: airmozilla-secrets
                key: inxpo.user_credentials
          - name: INXPO_SHOW_KEY
            valueFrom:
              secretKeyRef:
                name: airmozilla-secrets
                key: inxpo.show_key
          - name: INXPO_SHOW_PACKAGE_KEY
            valueFrom:
              secretKeyRef:
                name: airmozilla-secrets
                key: inxpo.show_package_key
