apiVersion: kustomize.config.k8s.io/v1beta1
namespace: airmozilla-prod
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
- cron.yaml
- sealed-secret.yaml
- hpa.yaml
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: itsre/airmozilla
  newTag: latest
