---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-c02c26fb23caccdc43f17018c03c955c7e0a6077
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-c02c26fb23caccdc43f17018c03c955c7e0a6077
        name: web
      initContainers:
      - image: itsre/airmozilla:master-c02c26fb23caccdc43f17018c03c955c7e0a6077
        name: migrate
