---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-38b099bcb4da6375e47313bbcf35cc3ccf139b0f
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-8fcd592f68bbf80e0a61192d19dd4b0b9d0c0e46
        name: web
      initContainers:
      - image: itsre/airmozilla:master-8fcd592f68bbf80e0a61192d19dd4b0b9d0c0e46
        name: migrate
