---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-ee3bc6ce33fc8f2c6bb31f2459ef231e0f726714
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-ee3bc6ce33fc8f2c6bb31f2459ef231e0f726714
        name: web
      initContainers:
      - image: itsre/airmozilla:master-ee3bc6ce33fc8f2c6bb31f2459ef231e0f726714
        name: migrate
