---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-d0dcd6efa0b7a42dcad4677978f80a12b8f58eac
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-d0dcd6efa0b7a42dcad4677978f80a12b8f58eac
        name: web
      initContainers:
      - image: itsre/airmozilla:master-d0dcd6efa0b7a42dcad4677978f80a12b8f58eac
        name: migrate
