---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-6cd8bc9602a6670a5e8c95dcccbeda33c1d94c6d
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-6cd8bc9602a6670a5e8c95dcccbeda33c1d94c6d
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-6cd8bc9602a6670a5e8c95dcccbeda33c1d94c6d
        name: migrate
