---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-0f08a7a695dc1e147ab4accfb60f8f199f50b3d2
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-0f08a7a695dc1e147ab4accfb60f8f199f50b3d2
        name: web
      initContainers:
      - image: itsre/airmozilla:master-0f08a7a695dc1e147ab4accfb60f8f199f50b3d2
        name: migrate
