---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-7ac073adc9387c3d347984cb9185fe08e01737a8
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-7ac073adc9387c3d347984cb9185fe08e01737a8
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-7ac073adc9387c3d347984cb9185fe08e01737a8
        name: migrate
