---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-7f0e827ceabb2c47ab8ef669c7a33cf2e483bc0c
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-7f0e827ceabb2c47ab8ef669c7a33cf2e483bc0c
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-7f0e827ceabb2c47ab8ef669c7a33cf2e483bc0c
        name: migrate
