---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-7fad72f77e217696295053fdbcc64a6b1bb47b60
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-7fad72f77e217696295053fdbcc64a6b1bb47b60
        name: web
      initContainers:
      - image: itsre/airmozilla:master-7fad72f77e217696295053fdbcc64a6b1bb47b60
        name: migrate
