---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-9d3b8201a099b907d0ddcf3e44f8f83af5c668ae
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: itsre/airmozilla:k8s-9d3b8201a099b907d0ddcf3e44f8f83af5c668ae
        name: web
