---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-9b3ea4e495a4030b8aa38025a460b805fa3d99ef
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-9b3ea4e495a4030b8aa38025a460b805fa3d99ef
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-9b3ea4e495a4030b8aa38025a460b805fa3d99ef
        name: migrate
