---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/airmozilla:master-fcd3137175c21c6d2143fd3853e1c140e0efa74c
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/airmozilla:master-fcd3137175c21c6d2143fd3853e1c140e0efa74c
        name: web
      initContainers:
      - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/airmozilla:master-fcd3137175c21c6d2143fd3853e1c140e0efa74c
        name: migrate
