---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-ef16b173d7a62f7660b3416681d8450da7bc391b
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-ef16b173d7a62f7660b3416681d8450da7bc391b
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-ef16b173d7a62f7660b3416681d8450da7bc391b
        name: migrate
