---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:master-92bf07da49ef9c24da4239077f258d133ac79c6a
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:master-92bf07da49ef9c24da4239077f258d133ac79c6a
        name: web
      initContainers:
      - image: itsre/airmozilla:master-92bf07da49ef9c24da4239077f258d133ac79c6a
        name: migrate
