---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-269a49ef3ccd28c73c0cf93c3e773c2f5cb383a6
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-269a49ef3ccd28c73c0cf93c3e773c2f5cb383a6
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-269a49ef3ccd28c73c0cf93c3e773c2f5cb383a6
        name: migrate
