---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-845d48e3b44ac77ebf6f99060cd72520fb8b1313
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-845d48e3b44ac77ebf6f99060cd72520fb8b1313
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-845d48e3b44ac77ebf6f99060cd72520fb8b1313
        name: migrate
