---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-00db6d3975c763e26b170f046583d5eca4f2d378
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-00db6d3975c763e26b170f046583d5eca4f2d378
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-00db6d3975c763e26b170f046583d5eca4f2d378
        name: migrate
