---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: events
  namespace: airmozilla-stage
spec:
  jobTemplate:
    spec:
      template:
        spec:
          $setElementOrder/containers:
          - name: events
          containers:
          - image: itsre/airmozilla:k8s-e47cf5af53efd905fe1f5bbc42e1b3af51023dd0
            name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airmozilla
  namespace: airmozilla-stage
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      $setElementOrder/initContainers:
      - name: migrate
      containers:
      - image: itsre/airmozilla:k8s-e47cf5af53efd905fe1f5bbc42e1b3af51023dd0
        name: web
      initContainers:
      - image: itsre/airmozilla:k8s-e47cf5af53efd905fe1f5bbc42e1b3af51023dd0
        name: migrate
