apiVersion: kustomize.config.k8s.io/v1beta1
namespace: airmozilla-stage
kind: Kustomization
bases:
 - ../common
patchesStrategicMerge:
 - ssl-patch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: airmozilla
  path: deployment-patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: Role
    name: nginx-ingress-role
  path: rbac-patch.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: airmozilla
  path: ingress-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
  path: nginx-args-patch.yaml
commonLabels:
  environment: stage
