- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --watch-namespace=airmozilla-stage
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --ingress-class=nginx-airmozilla-stage
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --update-status-on-shutdown=false
