---
- op: add
  path: /rules/0/verbs/-
  value: watch
- op: add
  path: /rules/0/verbs/-
  value: list
- op: add
  path: /rules/0/resources/-
  value : services
- op: add
  path: /rules/0/resources/-
  value : ingresses
- op: add
  path: /rules/0/resources/-
  value : endpoints
