---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:783633885093:certificate/bc328ba5-151e-4b97-a6ad-3b334f710097
  name: ingress-nginx
