---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:783633885093:certificate/a5b437a6-0734-4197-8196-e1e6aa738c3a
  name: ingress-nginx
